<?xml version="1.0" encoding="UTF-8"?>
<!--
    GO7 extension of IATA NDC 21.3.5 (not part of the IATA standard).
    Routes request built from standard IATA_OffersAndOrdersCommonTypes types.
-->
<xs:schema targetNamespace="http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersMessage"
           elementFormDefault="qualified"
           version="1.000"
           xmlns:cns="http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypes"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersMessage">
    <xs:import namespace="http://www.iata.org/IATA/2015/EASD/00/IATA_OffersAndOrdersCommonTypes"
               schemaLocation="IATA_OffersAndOrdersCommonTypes.xsd"/>

    <xs:element name="IATA_RoutesRQ">
        <xs:annotation>
            <xs:documentation>The Routes transaction returns the routes (origin and destination airport pairs) operated by the requested carriers.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:annotation>
                <xs:documentation>Routes RQ top level</xs:documentation>
            </xs:annotation>
            <xs:sequence>
                <xs:element name="DistributionChain" type="cns:DistributionChainType" minOccurs="1" maxOccurs="1">
                    <xs:annotation>
                        <xs:documentation>An instance of a distribution channel. That is, the set of organizations involved in the development of the current transaction.</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="PayloadAttributes" type="cns:IATA_PayloadStandardAttributesType" minOccurs="0" maxOccurs="1">
                    <xs:annotation>
                        <xs:documentation>IATA standard payload attributes.</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="Request" type="RoutesRequestType" minOccurs="1" maxOccurs="1">
                    <xs:annotation>
                        <xs:documentation>Routes request information.</xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="RoutesRequestType">
        <xs:sequence>
            <xs:element name="CarrierCriteria" type="cns:CarrierCriteriaType" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>Carriers whose routes are requested.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="OriginCode" type="cns:IATA_LocationCodeType" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>IATA airport code of the route departure.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="DestCode" type="cns:IATA_LocationCodeType" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>IATA airport code of the route arrival.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
