@startuml

actor "End customer" as customer

box GO7 #lightblue
    participant "go7-gateway" as gateway
end box

box PSS #pink
  participant "PSS" as pss
end box

autonumber

title Offer Context flow

== Use case: Find Available Routes ==
customer->gateway: query: Find Available Routes
note right
Show the routes options
Departure and Arrival airports
end note
gateway->customer: List of available routes

== Use case: Calendar Availability ==
customer->gateway: query: Calendar Availability
note right
Low fare calendar availability
Lowest price per flight date
end note
gateway->customer: List of calendar availabilities

== Use case: Flight Offers Search ==
customer->gateway: mutation: Flight Offers Search
note right
Flight offers search
Lists available flight offers
end note
opt If no offers in cache
gateway->pss:Request flight offers
pss->gateway:Flight offers
end
gateway->customer: List of flight offers

== Use case: Create Order ==
customer->gateway: mutation: Create order
note right
Create order for selected offer
Order information
end note
gateway->pss:Create order
pss->gateway: Order information
gateway->customer: Order information

== Use case: Update passenger information ==
customer->gateway: mutation: Update passenger information
note right
Update passenger information for selected offer
Order information
end note
gateway->pss:Update passenger information
pss->gateway: Updated order information
gateway->customer: Updated order information

== Use case: Service Offers Search ==
customer->gateway: mutation: Service Offers Search
note right
Search service offers by flight offer
Lists available service offers
end note
opt If no offers in cache
gateway->pss:Request service offers
pss->gateway:Service offers
end
gateway->customer: List of service offers

== Use case: Reserve service ==
customer->gateway: mutation: Reserve service
note right
Reserve service
Order information
end note
gateway->pss:Reserve service
pss->gateway:Order information with services
gateway->customer: Order information with services

== Use case: Seat Availability Search ==
customer->gateway: mutation: Seat Availability Search
note right
Search seat-map structure and seat offers
Seat-map and seat offers
end note
opt If no offers in cache
gateway->pss:Request seat offers
pss->gateway:Seat offers
end
gateway->customer: List of seat offers

== Use case: Reserve and Release Seat ==
customer->gateway: mutation: Reserve/release seat
note right
Reserve/release seat
Order structure
end note
gateway->pss:Reserve/release seat
pss->gateway:Order structure
gateway->customer: Order structure

== Use case: Get payment options ==
customer->gateway: mutation: Get payment options
note right
Get payment options
Payment options list
end note
gateway->customer: Payment options

== Use case: Confirm payment ==
customer->gateway: mutation: Confirm payment
note right
Confirm payment for selected type
Paid order information
end note
gateway->customer: Paid order information



@enduml